{% set name = "census" %}
{% set version = "0.8.12" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "8495a5700c5bd6a00bd456fb63a7cc3c98bb212ec6b9d0e78561d9fc8ebaa674" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - requests >=1.1.0
    - future
    - backports.functools_lru_cache  # [py<33]
    - setuptools

test:
  imports:
    - census
    - census.tests

about:
  home: http://github.com/sunlightlabs/census
  license_file: LICENSE
  license: BSD 3-Clause
  license_family: BSD
  summary: "A wrapper for the US Census Bureau's API"
  dev_url: http://github.com/sunlightlabs/census

extra:
  recipe-maintainers:
    - pmlandwehr
