{% set name = "census" %}
{% set version = "0.8.27" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 207aae0f83650004f6b7dab6a730b6a60df96a119f55167260c3153313f15a32

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools

  run:
    - python >={{ python_min }}
    - requests >=1.1.0
    - future
    - setuptools

test:
  imports:
    - census
    - census.tests
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://github.com/sunlightlabs/census
  license_file: LICENSE
  license: BSD-3-Clause
  license_family: BSD
  summary: A wrapper for the US Census Bureau's API
  dev_url: http://github.com/sunlightlabs/census

extra:
  recipe-maintainers:
    - pmlandwehr
    - jan-janssen
